-- Password - P@$$adminw0rd
INSERT INTO WIS.EMPLOYEE (LOGIN, PASSWORD, STATUS, "TYPE", CREATED_BY, CREATED_ON, VERSION) 
    VALUES ('admin', 'zGg9VlJJYuhILbOxBFPLU2C7hWkE7E093TeTwL6k0pw=', 1, 'Admin', 'Initiation', CURRENT_TIMESTAMP, 1);
INSERT INTO WIS.PERSONALDATA (EMPLOYEE_ID, EMAIL, EMPLOYEENUMBER, FIRSTNAME, LASTNAME, NOTIFICATIONPOINTS) 
    VALUES (1, 'admin@admin.pl', 'A1001', 'Adminimie', 'Adminnazwisko', 0);

-- Password - P@$$bartoszw0rd
INSERT INTO WIS.EMPLOYEE (LOGIN, PASSWORD, STATUS, "TYPE", LASTTYPE, CREATED_BY, CREATED_ON, VERSION) 
    VALUES ('bartosz', 'oSnChDGf0WCWUKyz+BsZPHsE7O0EHgUbfz6H9XIozhY=', 0, 'Disabled', 'Admin', 'Initiation', CURRENT_TIMESTAMP, 1);
INSERT INTO WIS.PERSONALDATA (EMPLOYEE_ID, EMAIL, EMPLOYEENUMBER, FIRSTNAME, LASTNAME, NOTIFICATIONPOINTS) 
    VALUES (2, 'bartosz@bartosz.pl', 'A1002', 'Bartosz', 'Bartoszewski', 0);

-- Password - P@$$impteamw0rd
INSERT INTO WIS.EMPLOYEE (LOGIN, PASSWORD, STATUS, "TYPE", CREATED_BY, CREATED_ON, VERSION) 
    VALUES ('impteam', '/esVsWAHs2ny0yGRi780c8EaTK4skfdJbMn+sT6CCw4=', 1, 'ImpTeam', 'Initiation', CURRENT_TIMESTAMP, 1);
INSERT INTO WIS.PERSONALDATA (EMPLOYEE_ID, EMAIL, EMPLOYEENUMBER, FIRSTNAME, LASTNAME, NOTIFICATIONPOINTS) 
    VALUES (3, 'impteam@impteam.pl', 'I1001', 'Impteamimie', 'Impteamnazwisko', 0);

-- Password - P@$$beataw0rd
INSERT INTO WIS.EMPLOYEE (LOGIN, PASSWORD, STATUS, "TYPE", LASTTYPE, CREATED_BY, CREATED_ON, VERSION) 
    VALUES ('beata', 'mxLWZAim24wU28aa3PB+kT6H37kYZIgA8ujjpcAYvig=', 0, 'Disabled', 'ImpTeam', 'Initiation', CURRENT_TIMESTAMP, 1);
INSERT INTO WIS.PERSONALDATA (EMPLOYEE_ID, EMAIL, EMPLOYEENUMBER, FIRSTNAME, LASTNAME, NOTIFICATIONPOINTS) 
    VALUES (4, 'beata@beata.pl', 'I1002', 'Beata', 'Beatowa', 0);

-- Password - P@$$employeew0rd
INSERT INTO WIS.EMPLOYEE (LOGIN, PASSWORD, STATUS, "TYPE", CREATED_BY, CREATED_ON, VERSION) 
    VALUES ('employee', 'DkQoH2Pae2Vqi1LgaF3RUJFTTRQf18qi96Kev/VnQpM=', 1, 'Employee', 'Initiation', CURRENT_TIMESTAMP, 1);
INSERT INTO WIS.PERSONALDATA (EMPLOYEE_ID, EMAIL, EMPLOYEENUMBER, FIRSTNAME, LASTNAME, NOTIFICATIONPOINTS) 
    VALUES (5, 'employee@employee.pl', 'E1001', 'Employeeimie', 'Employeenazwisko', 0);

-- Password - P@$$johnw0rd
INSERT INTO WIS.EMPLOYEE (LOGIN, PASSWORD, STATUS, "TYPE", CREATED_BY, CREATED_ON, VERSION) 
    VALUES ('john', 'mpvHiQXXyKcbpROYgNfaRbHQXWs2OXGNI5cc3/BTfBg=', 1, 'Employee', 'Initiation', CURRENT_TIMESTAMP, 1);
INSERT INTO WIS.PERSONALDATA (EMPLOYEE_ID, EMAIL, EMPLOYEENUMBER, FIRSTNAME, LASTNAME, NOTIFICATIONPOINTS) 
    VALUES (6, 'john@john.com', 'E1002', 'John', 'Johnowy', 0);
