-- USE THIS QUERY TO SELECT FROM SYS.SYSTABLE TABLE ALL TABLE AND CREATE QUERY TO DELETE FROM THEM
-- COPY THE QUERY FROM RESULT INTO COMMAND BOX AND RUN

SELECT 'DELETE FROM ' || schemaname ||'.' || tablename || ';'
FROM SYS.SYSTABLES
INNER JOIN SYS.SYSSCHEMAS ON SYS.SYSTABLES.SCHEMAID = SYS.SYSSCHEMAS.SCHEMAID
where schemaname='WIS';
